title:             Dumb Coder
email:             skkiss98@kaist.ac.kr
description:       Blog by Dumb
author:            Kim Seon gyu
baseurl:           "/startbootstrap-clean-blog-jekyll"
url:               "https:sklationd.github.io"

# Social Profiles
twitter_username:  
github_username:   sklationd
facebook_username: 김선규

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
